---
title: "Calibration Workshop"
author: "Sarah Lam"
date: "2023-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

```{r}
sager <- read.table(here("data", "sager.txt"), header=T)
sager = sager %>% mutate(date = paste(day,month,year, sep="/"))
sager$date = as.Date(sager$date,"%d/%m/%Y")

monthly_means <- sager %>% 
  group_by(wy, month) %>% 
  summarize(mean_obs = mean(obs), mean_model = mean(model))

mean_monthly_error <- monthly_means %>% 
  mutate(diff = mean_model-mean_obs) %>% 
  ungroup() %>% 
  summarize(mean(diff))

mme_corcoeff <- function(obs, model, wy, month){
new_frame <- cbind.data.frame(obs,model, wy, month)
monthly_means <- new_frame %>%
  #group by water year and month
  group_by(wy, month) %>%
  # take mean of model est. and observed values by month by water year
 summarize(mean_model=mean(model), mean_obs=mean(obs))
mean_monthly_error <- monthly_means %>%
  #take difference between mean model and mean obs values
  mutate(diff=mean_model-mean_obs) %>%
  ungroup()
mean_monthly_error <- abs(mean(mean_monthly_error$diff))
correlation <- cor(monthly_means$mean_model, monthly_means$mean_obs)
combined = .5*mean_monthly_error+ .5*correlation
return(combined)
}
mme_corcoeff(sager$obs, sager$model, sager$wy, sager$month)
```

```{r}
#correlation coefficient
cor_coeff <- cor(monthly_means$mean_model, monthly_means$mean_obs)

obs_mean_monthly_error <- abs(mean_monthly_error)

combined = .5*obs_mean_monthly_error + .5*cor_coeff
```

```{r}
#Calibration
msage = read.table("../Data/sagerm.txt", header=T)
nsim = ncol(msage)
snames = sprintf("S%d",seq(from=1, to=nsim))
colnames(msage)=snames
msage$date = sager$date
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy
msage = left_join(msage, sager[,c("obs","date")], by=c("date"))
msagel = msage %>% pivot_longer(cols=!c(date, month, year, day,wy), names_to="run", values_to="flow")
# p1=ggplot(subset(msagel, wy == 1970), aes(as.Date(date), flow, col=run))+geom_line()+theme(legend.position = "none")
# p1
#
# # lets add observed streamflow
# p1+geom_line(data=subset(sager, wy == 1970), aes(as.Date(date), obs), size=2, col="black", linetype=2)+labs(y="Streamflow", x="Date")
# subset for split sample calibration
short_msage = subset(msage, wy < 1975)
# compute performance measures for output from all parameters
res = short_msage %>% select(!c("date","month","year","day","wy","obs")) %>%
      map_dbl(mme_corcoeff, short_msage$obs, short_msage$wy, short_msage$month) # purrr function here! map_dbl will apply the function nse() to each column in our data frame against the observed and returns a vector
head(res)
best <- which.max(res)
worst <- which.min(res) 
```

```{r}
# graph results of best model compared to observed data

ggplot(msage, aes(date, S95))+ geom_line(aes(col = "model"))+
  geom_line(aes(date, obs, col = "observed")) +
  labs(x = "Date", 
       y = "Stream Flow mm/day")
```


